name: "Gito: AI Code Reviewer"
on: { pull_request: { types: [opened, synchronize, reopened] } }
jobs:
  review:
    runs-on: ubuntu-latest
    permissions: { contents: read, pull-requests: write } # 'write' for leaving the summary comment
    steps:
    - uses: actions/checkout@v4
      with: { fetch-depth: 0 }
    - name: Set up Python
      uses: actions/setup-python@v5
      with: { python-version: "3.13" }
    - name: Install Gito
      run: |
        pip install poetry
        poetry install
        echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
        # installation from PYPI:
        # pip install gito.bot~=2.0
    - name: Run AI code review
      env:
        # OpenAI Setup:
        # LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
        # LLM_API_TYPE: openai
        # MODEL: "gpt-4.1"
        LLM_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        LLM_API_TYPE: anthropic
        MODEL: "claude-sonnet-4-20250514"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        JIRA_URL: ${{ secrets.JIRA_URL }}
        JIRA_USER: ${{ secrets.JIRA_USER }}
      run: |
        gito --verbose review
        gito github-comment --token "$GITHUB_TOKEN"
    - uses: actions/upload-artifact@v4
      with:
        name: gito-code-review-results
        path: |
          code-review-report.md
          code-review-report.json